

logging:
  file: application.log
  path:
  level:
    root: info
    com.lifengdi.store.client: DEBUG

server:
  port: 8081


elasticsearch:
  host: jd
  port: 9201
  scheme: http
  charset: UTF-8
  token: esToken

  client:
    connectTimeOut: 5000
    socketTimeout: 15000


spring:
  data:
    elasticsearch:
      cluster-nodes: jd:9300
      cluster-name: JD
