
logging:
  file: application.log
  path:
  level:
    root: info
    com.lifengdi.store.client: DEBUG

server:
  port: 8081


elasticsearch:
  host: jd
  port: 9201
  scheme: http
  charset: UTF-8
  token: esToken

  client:
    connectTimeOut: 5000
    socketTimeout: 15000


spring:
  # jdbc_config   datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://fnjkj1:3306/bicycle_admin_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=true

    # Hikari will use the above plus the following to setup connection pooling
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCPDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.chan.mapper
